server:
  port: 1947
  error:
    include-message: always

spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 35.247.170.16
  datasource:
    url: jdbc:postgresql://34.126.137.107:5432/travelmarketplace
    username: postgres
    password: capstonevlu
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
