server:
  port: 1947
  error:
    include-message: always

spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 35.240.226.176
  datasource:
    url: jdbc:postgresql://localhost:5432/travelmarketplace
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
